#!/usr/bin/env node
'use strict';

/*
 * This is the entry point for the CLI. Here commands and options are parsed and the associated code is run.
 */

const program = require('commander');

program.version('0.0.1')
  .command('configure', 'Set up User ID and Secret')
  .command('generate', 'Create a resources template')
  .command('deploy', 'Deploy resources to Forge')
  .command('da', 'Design automation API commands');

program.parse(process.argv);
