#!/usr/bin/env node
'use strict';

const deployResources = require('../modules/deploy').deployResources;
const printDeployPlan = require('../modules/deploy').printDeployPlan;
const program = require('commander');

program.description('Deploy resources to Forge')
  .option('-p, --plan', `Display a deploy plan without deploying anything`);

program.parse(process.argv);

if (program.plan) {
  printDeployPlan();
} else {
  deployResources();
}

